# Generated by Django 2.0.7 on 2018-08-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180717_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category'),
        ),
    ]
